version: '3'

networks: 
  default: 
    external: 
      name: local_network_dev 

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    command: [nginx-debug, '-g', 'daemon off;']  
    ports:
      - 8080:8080
    networks:
      default:
        ipv4_address: 192.168.0.3

  web:
    build: .
    ports:
      - "8000:5000"
    networks:
      default:
        ipv4_address: 192.168.0.4

  redis:
    image: "redis:alpine"
    networks:
      default:
        ipv4_address: 192.168.0.5